server:
  port: 8282
logging:
  level:
    org.springframework: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans

index-service:
  rest:
    enabled: true
stubrunner:
  idsToServiceIds:
    trade-service: trade-service
  ids: 'com.example.spring.cloud:trade-service:+:stubs'
spring:
  application:
    name: index-service
eureka:
    client:
      enabled: true
    instance:
        hostname: ${vcap.services.eureka-service.credentials.uri:http://eureka-server:8761}/eureka/